# 注意：号的前面一定要有一个空格
server:
  port: 8088
datasource:
  driverName: mysql
  host: 192.168.10.28
  port: 3306
  database: goadmin
  username: root
  password: Aa778899
  charset: utf8
  loc: Asia/Shanghai
