definitions:
  model.Book:
    properties:
      author:
        example: 作者
        type: string
      createAt:
        example: 创建时间
        type: string
      desc:
        example: 描述
        type: string
      id:
        type: integer
      title:
        example: 书籍名称
        type: string
      updateAt:
        example: 更新时间
        type: string
      year:
        example: 年份
        type: string
    type: object
  model.Film:
    properties:
      actor:
        example: 演员
        type: string
      address:
        example: 出品地区
        type: string
      createAt:
        example: 创建时间
        type: string
      desc:
        example: 描述
        type: string
      id:
        type: integer
      name:
        example: 电影名称
        type: string
      updateAt:
        example: 更新时间
        type: string
      year:
        example: 年份
        type: string
    type: object
  model.User:
    properties:
      createAt:
        example: 创建时间
        type: string
      desc:
        type: string
      id:
        type: integer
      ip:
        type: string
      name:
        example: 用户名称
        type: string
      password:
        description: 字段不暴露给用户，则使用 `json:"-"` 修饰
        example: 密码
        type: string
      telephone:
        example: 手机号码
        type: string
      updateAt:
        example: 更新时间
        type: string
    type: object
  model.UserDto:
    properties:
      createAt:
        example: 创建时间
        type: string
      desc:
        type: string
      name:
        type: string
      telephone:
        type: string
      updateAt:
        example: 更新时间
        type: string
    type: object
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT //localhost:80
  termsOfService: 运行地址：http://localhost/swagger/index.html
  title: Golang Gin API
  version: "2.0"
paths:
  /api/auth/info:
    get:
      consumes:
      - application/json
      description: 用户信息
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: telephone
        in: query
        name: telephone
        type: string
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserDto'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 单个用户信息
      tags:
      - 用户
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 用户登陆
      parameters:
      - description: telephone
        in: query
        name: telephone
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 用户登陆
      tags:
      - 用户
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      - description: telephone
        in: query
        name: telephone
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 用户注册
      tags:
      - 用户
  /api/books:
    get:
      consumes:
      - application/json
      description: 书籍列表
      parameters:
      - description: title
        in: query
        name: name
        type: string
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 获取书籍列表
      tags:
      - 书籍
    post:
      consumes:
      - application/json
      description: 创建书籍
      parameters:
      - description: title
        in: query
        name: name
        type: string
      - description: year
        in: query
        name: year
        type: string
      - description: author
        in: query
        name: actor
        type: string
      - description: desc
        in: query
        name: desc
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 创建书籍列表
      tags:
      - 书籍
  /api/books/{id}:
    delete:
      consumes:
      - application/json
      description: 书籍列表
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
        "400":
          description: '{ "code": 400, "message": "id必传" }'
          schema:
            type: string
      summary: 删除书籍列表
      tags:
      - 书籍
    put:
      consumes:
      - application/json
      description: 书籍列表
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
        "400":
          description: '{ "code": 400, "message": "id必传" }'
          schema:
            type: string
      summary: 更新书籍列表
      tags:
      - 书籍
  /api/films:
    get:
      consumes:
      - application/json
      description: 电影列表
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Film'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 获取电影列表
      tags:
      - 电影
    post:
      consumes:
      - application/json
      description: 创建电影
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: year
        in: query
        name: year
        type: string
      - description: address
        in: query
        name: address
        type: string
      - description: actor
        in: query
        name: actor
        type: string
      - description: desc
        in: query
        name: desc
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Film'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 创建电影列表
      tags:
      - 电影
  /api/films/{id}:
    delete:
      consumes:
      - application/json
      description: 电影列表
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Film'
        "400":
          description: '{ "code": 400, "message": "id必传" }'
          schema:
            type: string
      summary: 删除电影列表
      tags:
      - 电影
    put:
      consumes:
      - application/json
      description: 电影列表
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Film'
        "400":
          description: '{ "code": 400, "message": "id必传" }'
          schema:
            type: string
      summary: 更新电影列表
      tags:
      - 电影
  /api/getCode:
    get:
      consumes:
      - application/json
      description: 获取验证码
      produces:
      - application/json
      responses:
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 获取验证码
      tags:
      - 验证码
  /api/upload:
    post:
      consumes:
      - multipart/form-data
      description: 文件上传
      parameters:
      - description: file
        in: query
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "message": "上传成功" }'
          schema:
            type: string
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 文件上传
      tags:
      - 文件上传
  /api/users:
    get:
      consumes:
      - application/json
      description: 用户列表
      parameters:
      - description: name
        in: query
        name: name
        type: string
      - description: telephone
        in: query
        name: telephone
        type: string
      - description: pageNum
        in: query
        name: pageNum
        required: true
        type: string
      - description: pageSize
        in: query
        name: pageSize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户
  /api/users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: '{ "code": 400, "message": "请求失败" }'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户
    put:
      consumes:
      - application/json
      description: 用户信息
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: '{ "code": 400, "message": "id必传" }'
          schema:
            type: string
      summary: 更新用户信息
      tags:
      - 用户
swagger: "2.0"
